### ISSUE TITLE
Mounting a disk reboots the ADAM

### ISSUE THREAD

**Issue by KPreston2900050** [alekmaul/emultwo#1]
For some reason the system has this uncontrollable idea that when you mount a disk that it is supposed to boot it.

Exactly how are you supposed to change disks if you are working on something.

I come off as having a bad attitude sometimes but what I am really thinking is that you found this shell somewhere on the internet, modified it to run Colecovision and ADAM at some point and really have no clue as to how it works.

There is no way you wrote this thing from the beginning.

This disk issue is a prime example.
No one in their right mind puts a disk in the drive just for the entire computer to reset itself.

Amazing...freaking amazing

**Comment by alekmaul** [comment]
If you take a look at main page, you have a Credit Part regarding from whom the source code is used regarding the Adam Part.
